[package]
name = "wwl"
version = "0.1.0"
edition = "2021"

[dependencies]
pyo3 = { version = "0.26", features = ["auto-initialize"] }
numpy = "0.26"
ndarray = "0.15"
petgraph = "0.8"
pythonize = "0.26"
